### ISSUE TITLE
[Task] 메인 화면 작성

### ISSUE THREAD

**Issue by rkems0122** [codestates/todaysmovie#7]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Main.js 작성

### TODO
1. [ ] 저장된 영화가 없으면 영화 추가 요구 버튼을 보여주어야 합니다.
2. [ ] 랜덤 선택 버튼, my profile 버튼이 있어야 합니다.
3. [ ] 랜덤 선턱 버튼을 누르면 임의로 영화가 하나 나와야 합니다.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `High`
