### ISSUE TITLE
[Task] 배포

### ISSUE THREAD

**Issue by rkems0122** [codestates/todaysmovie#9]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [ ] http 기본 배포를 진행합니다
2. [ ] EC2 설정을 합니다.
3. [ ] S3 버킷 설정을 완료합니다

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint__3`
- Urgency: `High`
